services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser@%'
      - 'MYSQL_ROOT_HOST=%'
    ports:
      - '3306:3306'
    expose:
      - '3306'