openapi: "3.0.3"
info:
  title: "iotApp API"
  description: "iotApp API"
  version: "1.0.0"
servers:
  - url: "https://iotApp"
paths:
  /api/auth/signin:
    post:
      summary: "POST api/auth/signin"
      operationId: "authenticateUser"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /api/auth/signup:
    post:
      summary: "POST api/auth/signup"
      operationId: "registerUser"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    LoginRequest:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
    RegisterRequest:
      type: "object"
      properties:
        username:
          type: "string"
        email:
          type: "string"
        roles:
          type: "array"
          items:
            type: "string"
        password:
          type: "string"