name: AzureSpringApps

on:
  push:
    branches:
      - main

env:
  ASC_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_SUBSCRIPTION: b1f96fa5-cc4a-4d11-baca-c6aa98447e79

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and install local artifact
        run: |
          cd src/main/gen
          mvn install

      - name: Maven build, clean, with no tests
        run: |
          mvn clean package -DskipTests

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List JAR files
        run: |
          find ${{ env.ASC_PACKAGE_PATH }} -name "*.jar"

      - name: Deploy to production with artifact
        uses: azure/spring-apps-deploy@v1
        with:
          azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          action: Deploy
          service-name: iot-app
          app-name: iot-backend
          use-staging-deployment: false
          package: ${{ env.ASC_PACKAGE_PATH }}/target/*.jar

