name: Build and Deploy to Raspberry Pi

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-save:
    runs-on: ubuntu-latest
    environment:
      name: 'RaspberryPi'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -Pprod clean package -DskipTests

      - name: Build Docker image
        run: docker build -t iot-app:back .

      - name: Save Docker image
        run: docker save iot-app:back

  transfer:
    needs: build-and-save
    runs-on: ubuntu-latest
    environment:
      name: 'RaspberryPi'
    steps:
      - uses: actions/checkout@main
      - name: Copy image to Raspberry Pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USERNAME }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_PORT }}
          source: "."
          target: "/home/dfurchert/iotApp/"

  deploy:
    needs: transfer
    runs-on: ubuntu-latest
    environment:
      name: 'RaspberryPi'
    steps:
      - name: Stop and Remove Old Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USERNAME }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_PORT }}
          script: |
            cd iotApp/
            docker stop iotapp-backend-1 || true
            docker rm iotapp-backend-1 || true

      - name: Replace Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USERNAME }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_PORT }}
          script: |
            cd iotApp/
            docker rmi iot-app:back || true
            docker load -i back-iot-image

      - name: Start Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USERNAME }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_PORT }}
          script: |
            cd iotApp/
            docker compose up -d

      - name: Wait for Services to Stabilize
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USERNAME }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_PORT }}
          script: sleep 300

      - name: Restart Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USERNAME }}
          key: ${{ secrets.RPI_SSH_KEY }}
          port: ${{ secrets.RPI_PORT }}
          script: |
            cd iotApp/
            docker compose restart